spring.application.name=jpademo
Spring.datasource.url=jdbc:mysql://localhost:3306/demodb
Spring.datasource.password=Musaib@123
Spring.datasource.username=root
Spring.jpa.hibernate.ddl-auto=update
Spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE